# Generated by Django 3.2 on 2021-04-12 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuestoVacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('nombre_ips', models.CharField(max_length=50)),
                ('telefono_1', models.CharField(max_length=30)),
                ('horario_de_atencion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('identificacion', models.CharField(max_length=30)),
                ('titulo_profesional', models.CharField(max_length=40)),
                ('codigo_profesional', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPoblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
                ('codigo_de_vacunacion', models.CharField(max_length=15)),
                ('regimen', models.CharField(choices=[('contributivo', 'Contributivo'), ('subsidiado', 'Subsidiado')], default='contributivo', max_length=32)),
                ('ESTADO', models.CharField(choices=[('no_vacunado', 'No Vacunado'), ('proceso_iniciado', 'Proceso de vacunación iniciado'), ('vacunado', 'Vacunado')], default='contributivo', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CompuestoVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=30)),
                ('codigo_fabricante', models.CharField(max_length=20)),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('dosis', models.CharField(choices=[('primera', 'Primera dosis'), ('segunda', 'Segunda dosis')], default='primera', max_length=32)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='service.usuariopoblacion')),
                ('puesto_vacunacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puesto_vacunacion', to='service.puestovacunacion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='service.responsablevacuna')),
            ],
        ),
    ]
