# Generated by Django 3.2 on 2021-04-13 04:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsablevacuna',
            old_name='identificacion',
            new_name='numero_identificacion',
        ),
        migrations.RemoveField(
            model_name='compuestovacuna',
            name='puesto_vacunacion',
        ),
        migrations.RemoveField(
            model_name='usuariopoblacion',
            name='ESTADO',
        ),
        migrations.AddField(
            model_name='compuestovacuna',
            name='consentimiento_informado',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puestovacunacion',
            name='telefono_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopoblacion',
            name='estado',
            field=models.CharField(choices=[('no_vacunado', 'No Vacunado'), ('proceso_iniciado', 'Proceso de vacunación iniciado'), ('vacunado', 'Vacunado')], default='no_vacunado', max_length=32),
        ),
        migrations.AddField(
            model_name='usuariopoblacion',
            name='puesto_vacunacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='puesto_vacunacion', to='service.puestovacunacion'),
            preserve_default=False,
        ),
    ]
