# Generated by Django 3.2 on 2021-04-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210412_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestovacunacion',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puestovacunacion',
            name='horario_de_atencion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='puestovacunacion',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='puestovacunacion',
            name='telefono_1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuariopoblacion',
            name='ciudad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariopoblacion',
            name='departamento',
            field=models.CharField(max_length=50),
        ),
    ]
